#!/usr/bin/env python3
"""
quick_dash.py — Quick Dashboard Builder
Part of: GLA-Tools

Builds a throw-away GLA dashboard specialist from quick_config.json.
No LLM involved — deterministic assembly from fixed code blocks.

Usage:
    python quick_dash.py              # build specialist from quick_config.json
    python quick_dash.py --fields     # print available fields as JSON (used by config.ps1)
"""

import sys
import json
import time
import subprocess
from pathlib import Path
from datetime import date, timedelta

CONFIG_FILE = Path(__file__).parent / "quick_config.json"

# ══════════════════════════════════════════════════════════════════════════════
#  GLA import helper
# ══════════════════════════════════════════════════════════════════════════════

def _load_config() -> dict:
    if not CONFIG_FILE.exists():
        print("[Error] quick_config.json not found. Run config.ps1 first.")
        sys.exit(1)
    return json.loads(CONFIG_FILE.read_text(encoding="utf-8"))


def _import_gla_maps(gla_path: str):
    gla = Path(gla_path)
    if not gla.exists():
        print(f"[Error] GLA path not found: {gla_path}")
        sys.exit(1)
    if str(gla) not in sys.path:
        sys.path.insert(0, str(gla))
    try:
        from maps import field_map, context_map
        return field_map, context_map
    except ImportError as e:
        print(f"[Error] GLA modules not importable: {e}")
        sys.exit(1)


# ══════════════════════════════════════════════════════════════════════════════
#  Field classification
# ══════════════════════════════════════════════════════════════════════════════

def _classify_fields(gla_path: str, mode: str) -> dict:
    """
    Return available fields split by type.
    mode: "intraday" or "overview"
    """
    field_map, context_map = _import_gla_maps(gla_path)

    # Import garmin_map directly to inspect field definitions
    from maps import garmin_map

    garmin_daily   = []
    garmin_intraday = []

    for f in field_map.list_fields():
        defn = garmin_map._FIELD_MAP.get(f, {})
        has_intraday = defn.get("intraday") is not None
        has_daily    = defn.get("daily") is not None or defn.get("raw_pct") is not None
        if mode == "intraday" and has_intraday:
            garmin_intraday.append(f)
        elif mode == "overview" and has_daily:
            garmin_daily.append(f)

    context_fields = []
    for source in context_map.list_sources():
        for f in context_map.list_fields(source):
            context_fields.append({"field": f, "source": source})

    return {
        "garmin":  garmin_intraday if mode == "intraday" else garmin_daily,
        "context": context_fields,
    }


# ══════════════════════════════════════════════════════════════════════════════
#  --fields: print available fields as JSON for config.ps1
# ══════════════════════════════════════════════════════════════════════════════

def cmd_fields():
    cfg  = _load_config()
    mode = cfg.get("mode", "overview")
    gla  = cfg.get("gla_path", "")
    fields = _classify_fields(gla, mode)
    print(json.dumps(fields))


# ══════════════════════════════════════════════════════════════════════════════
#  Code block library — fixed patterns, no generation
# ══════════════════════════════════════════════════════════════════════════════

_HEADER = '''\
#!/usr/bin/env python3
"""
{filename}

Quick specialist — generated by GLA-Tools/quick_dash.
Mode: {mode}
Fields: {field_list}
"""

import sys
from pathlib import Path

sys.path.insert(0, r"{gla_path}")
'''

_IMPORT_FIELD_MAP = "from maps.field_map   import get as field_get\n"
_IMPORT_CONTEXT_MAP = "from maps.context_map import get as context_get\n"

_META = '''
META = {{
    "name":        "{name}",
    "description": "{description}",
    "source":      "{source}",
    "formats": {{
{formats}
    }},
}}

'''

_GARMIN_FIELDS_DECL = "_GARMIN_FIELDS = [\n{entries}]\n\n"
_CONTEXT_FIELDS_DECL = "_CONTEXT_FIELDS = [\n{entries}]\n\n"

_BUILD_OVERVIEW = '''\
def build(date_from: str, date_to: str, settings: dict) -> dict:
    fields_out = []

    for f in _GARMIN_FIELDS:
        result = field_get(f["field"], date_from, date_to, resolution="daily")
        garmin = result.get("garmin", {})
        days = [
            {"date": entry["date"], "value": entry["value"]}
            for entry in garmin.get("values", [])
        ]
        fields_out.append({
            "field": f["field"],
            "label": f["label"],
            "unit":  f["unit"],
            "group": f["group"],
            "days":  days,
        })

    for f in _CONTEXT_FIELDS:
        result = context_get(f["field"], date_from, date_to)
        source_result = next(iter(result.values()), {}) if result else {}
        days = [
            {"date": entry["date"], "value": entry["value"]}
            for entry in source_result.get("values", [])
        ]
        fields_out.append({
            "field": f["field"],
            "label": f["label"],
            "unit":  f["unit"],
            "group": f["group"],
            "days":  days,
        })

    return {
        "title":    "{title}",
        "subtitle": f"{date_from} \\u2192 {date_to}",
        "date_from": date_from,
        "date_to":   date_to,
        "fields":   fields_out,
    }
'''

_BUILD_INTRADAY = '''\
def build(date_from: str, date_to: str, settings: dict) -> dict:
    fields_out = []

    for f in _GARMIN_FIELDS:
        result = field_get(f["field"], date_from, date_to, resolution="intraday")
        garmin = result.get("garmin", {})
        series_raw = []
        for day_entry in garmin.get("values", []):
            day_series = day_entry.get("series")
            if isinstance(day_series, list):
                series_raw.extend(day_series)

        # Hourly aggregation for HTML/JSON — average per hour
        hourly = {}
        for entry in series_raw:
            hour_key = entry["ts"][:13]  # "2026-04-04T14"
            if hour_key not in hourly:
                hourly[hour_key] = []
            hourly[hour_key].append(entry["value"])
        days = [
            {"date": f"{h}:00:00", "value": round(sum(v) / len(v), 1)}
            for h, v in sorted(hourly.items())
        ]

        # series_hourly: aggregated for HTML timeseries chart
        series_hourly = [
            {"ts": f"{h}:00:00", "value": round(sum(v) / len(v), 1)}
            for h, v in sorted(hourly.items())
        ]

        fields_out.append({
            "field":  f["field"],
            "label":  f["label"],
            "unit":   f["unit"],
            "group":  f["group"],
            "series": series_hourly,  # hourly -- for HTML timeseries chart
            "series_raw": series_raw, # raw    -- for Excel
        })

    return {
        "title":    "{title}",
        "subtitle": f"{date_from} \\u2192 {date_to}",
        "date_from": date_from,
        "date_to":   date_to,
        "fields":   fields_out,
    }
'''

# ══════════════════════════════════════════════════════════════════════════════
#  Format → filename + META entry helpers
# ══════════════════════════════════════════════════════════════════════════════

_FORMAT_EXT = {
    "html":         ".html",
    "html_complex": ".html",
    "html_mobile":  ".html",
    "excel":        ".xlsx",
    "json":         ".json",
    "pdf":          ".pdf",
    "word":         ".docx",
}

def _format_lines(formats: list, timestamp: int) -> str:
    lines = []
    for fmt in formats:
        ext = _FORMAT_EXT.get(fmt, ".html")
        lines.append(f'        "{fmt}": "quick_{timestamp}_{fmt}{ext}",')
    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
#  Field metadata helpers
# ══════════════════════════════════════════════════════════════════════════════

_UNITS = {
    "heart_rate_series":    "bpm",
    "stress_series":        "level",
    "spo2_series":          "%",
    "body_battery_series":  "level",
    "respiration_series":   "brpm",
    "hrv_last_night":       "ms",
    "resting_heart_rate":   "bpm",
    "stress_avg":           "level",
    "body_battery_max":     "level",
    "spo2_avg":             "%",
    "sleep_duration":       "h",
    "sleep_score":          "pts",
    "sleep_deep_pct":       "%",
    "sleep_light_pct":      "%",
    "sleep_rem_pct":        "%",
    "sleep_awake_pct":      "%",
    "vo2max":               "ml/kg/min",
    "sleep_score_feedback": "",
    "sleep_score_qualifier":"",
    # context
    "temperature_max":      "°C",
    "temperature_min":      "°C",
    "temperature_avg":      "°C",
    "precipitation":        "mm",
    "precipitation_sum":    "mm",
    "sunshine_duration":    "min",
    "sunshine_sum":         "min",
    "uv_index_max":         "",
    "wind_speed_max":       "km/h",
    "wind_gust_max":        "km/h",
    "cloud_cover_avg":      "%",
    "humidity_avg":         "%",
    "pressure_avg":         "hPa",
    "condition":            "",
    "pollen_birch":         "idx",
    "pollen_alder":         "idx",
    "pollen_grass":         "idx",
    "pollen_mugwort":       "idx",
    "pollen_olive":         "idx",
    "pollen_ragweed":       "idx",
    "airquality_pm2_5":     "µg/m³",
    "airquality_pm10":      "µg/m³",
    "airquality_european_aqi": "idx",
    "airquality_nitrogen_dioxide": "µg/m³",
    "airquality_ozone":     "µg/m³",
}

def _label(field: str) -> str:
    return field.replace("_", " ").title()

def _unit(field: str) -> str:
    return _UNITS.get(field, "")

def _group(field: str, context_fields: list) -> str:
    ctx_names = {f["field"]: f["source"] for f in context_fields}
    return ctx_names.get(field, "garmin")


# ══════════════════════════════════════════════════════════════════════════════
#  Assemble specialist
# ══════════════════════════════════════════════════════════════════════════════

def _assemble(cfg: dict, timestamp: int) -> str:
    name        = cfg["name"]
    description = cfg.get("description", "")
    mode        = cfg["mode"]
    formats     = cfg["formats"]
    garmin_sel  = cfg["garmin_fields"]
    context_sel = cfg["context_fields"]

    filename   = f"quick_{timestamp}_dash.py"
    field_list = ", ".join(garmin_sel + context_sel)

    needs_context = bool(context_sel)
    needs_garmin  = bool(garmin_sel)

    source_parts = []
    if needs_garmin:
        source_parts.append("Garmin")
    if needs_context:
        source_parts.append("context_data/")
    source = " + ".join(source_parts)

    gla_path_escaped = cfg.get("gla_path", "").replace("\\", "\\\\")
    code = _HEADER.format(
        filename=filename,
        mode=mode,
        field_list=field_list,
        gla_path=gla_path_escaped,
    )

    if needs_garmin:
        code += _IMPORT_FIELD_MAP
    if needs_context:
        code += _IMPORT_CONTEXT_MAP

    fmt_lines = _format_lines(formats, timestamp)
    code += _META.format(
        name=name,
        description=description,
        source=source,
        formats=fmt_lines,
    )

    if needs_garmin:
        entries = ""
        for f in garmin_sel:
            entries += (
                f'    {{"field": "{f}", '
                f'"label": "{_label(f)}", '
                f'"unit": "{_unit(f)}", '
                f'"group": "garmin"}},\n'
            )
        code += _GARMIN_FIELDS_DECL.format(entries=entries)

    if needs_context:
        entries = ""
        for f in context_sel:
            grp = _group(f, cfg.get("_context_meta", []))
            entries += (
                f'    {{"field": "{f}", '
                f'"label": "{_label(f)}", '
                f'"unit": "{_unit(f)}", '
                f'"group": "{grp}"}},\n'
            )
        code += _CONTEXT_FIELDS_DECL.format(entries=entries)

    if mode == "intraday":
        build_block = _BUILD_INTRADAY
    else:
        build_block = _BUILD_OVERVIEW

    # Inject title — replace placeholder
    build_block = build_block.replace("{title}", name)

    # Remove context loop if not needed
    if not needs_context and "_CONTEXT_FIELDS" in build_block:
        # Strip the context for-loop block
        lines = build_block.splitlines()
        out, skip = [], False
        for line in lines:
            if "for f in _CONTEXT_FIELDS:" in line:
                skip = True
            if skip and line.strip() == "" and not any(
                "for f in _CONTEXT_FIELDS" in l for l in lines
            ):
                skip = False
                continue
            if not skip:
                out.append(line)
        build_block = "\n".join(out)

    # Remove garmin loop if not needed
    if not needs_garmin and "_GARMIN_FIELDS" in build_block:
        lines = build_block.splitlines()
        out, skip = [], False
        for line in lines:
            if "for f in _GARMIN_FIELDS:" in line:
                skip = True
            if skip and line.strip() == "":
                skip = False
                continue
            if not skip:
                out.append(line)
        build_block = "\n".join(out)

    code += build_block
    return code


# ══════════════════════════════════════════════════════════════════════════════
#  Build
# ══════════════════════════════════════════════════════════════════════════════

def cmd_build():
    cfg = _load_config()

    output_dir = Path(__file__).parent / "scripts"
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = int(time.time())
    code      = _assemble(cfg, timestamp)

    out_path = output_dir / f"quick_{timestamp}_dash.py"
    out_path.write_text(code, encoding="utf-8")

    print(f"[OK] Specialist written: {out_path.name}")

    # Hand off to quick_run.py
    runner = Path(__file__).parent / "quick_run.py"
    subprocess.run([sys.executable, str(runner)])


# ══════════════════════════════════════════════════════════════════════════════
#  Entry point
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    arg = sys.argv[1] if len(sys.argv) > 1 else None
    if arg == "--fields":
        cmd_fields()
    elif arg is None:
        cmd_build()
    else:
        print(f"[Error] Unknown argument: {arg}")
        print("Usage: python quick_dash.py [--fields]")
        sys.exit(1)
